#! /bin/bash
#Author: Mohan
#Date created: 07/28/2020
#Description: Run basic linux tasks
#Date Modified: 07/28/2020
echo
echo This script will run  a few basic tasks
echo



pwd
echo
ls
echo
whoami
echo
date
echo
cal
echo
touch a b c
echo End of script

