#! /bin/bash
# Author: Mohan
# Date: 08/12/2020
# Description: This script will check the files
# Modified: 08/12/2020

FILES="/etc/passwd
      /etc/group
     /etc/shadow
    /etc/sshd_ssh_config
    /etc/fake"
echo
for file in $FILES
do
  if [ ! -e $file ]
  then
  echo $file do not exis
  echo
  fi
done
