#! /bin/bash
# Author: Mohan
# Date: 08/08/2020
# Description: This script will check for disk space
# Modified: 08/08/2020

a=`df -h | egrep -v "tmpfs|devtmpfs" | tail -n+2 | awk '{print $5}' | cut -d'%' -f1`

for i in $a
do	
	if [ $i -ge 5 ]
	then
	echo check disk space $i `df -h | grep $i`
fi
done

