#! /bin/bash
# Author: Mohan
# Date: 08/08/20202
# Description: This script will create a user account with description,ID and check
# Modified: 08/08/2020

echo "Please provide a username?"
read u
echo

grep -q $u /etc/passwd
     if [ $? -eq 0 ]
     then
     echo ERROR --user $u already exist
     echo Please choose another username
     echo
     exit 0
     fi

echo "Please provide a user description?"
read d
echo
echo "Do you want to specify user ID (y/n)?"
read ynu
echo
if [ $ynu == y ]
then
echo "Please enter UID?"
read uid
sudo useradd $u -c "$d" -u $uid
echo
echo $u account has been created
elif [ $ynu == n ]
then echo No worries we will assign a UID
sudo useradd $u -c "$d"
echo
echo $u account has been created
fi

