#! /bin/bash
# Author: Mohan
# Date:
# Description: This scriptn will list users logged in by user input
# Modified:

echo "Please enter day( e.g Mon)"
read d
echo
echo "Please enter month(e.g Aug)" 
read m
echo
echo "Please enter date(e.g 28)"
read da
echo
last | grep "$d $m $da" | awk '{print $1}'
