#! /bin/bash
# Author: Mohan
# Date: 08/08/2020
# Description: This scriptn will list users logged in by date
# Modified: 08/08/2020

today=`date | awk '{print $1,$2,$3}'`
last | grep "$today" | awk '{print $1}'
