#! /bin/bash
# Author: MOhan
# Date: 08/08/2020
# Description: This script will ping a remote host and notify
# Modified: 08/08/2020

hosts="192.168.1.36"
ping -c1 $hosts &> /dev/null
      if [ $? -eq 0 ]
      then
      echo $hosts is  OK
      else
      echo $hosts is  NOT ok
      fi
