#! /bin/bash
# Author: MOhan
# Date: 08/08/2020
# Description: This script will ping multiple remote hosts and notify
# Modified: 08/08/2020

hosts="/home/mohan/ps/myhosts"
for ip in $(cat $hosts)
     do
ping -c1 $ip &> /dev/null
      if [ $? -eq 0 ]
      then
      echo $ip is  OK
      else
      echo $ip is  NOT ok
      fi
done
